openapi: 3.0.3
info:
  title: Calculadora de Empréstimos API
  description: API REST para cálculo de empréstimos com sistema PRICE
  version: 1.0.0
  contact:
    name: DevIO
    email: contato@devio.com.br

servers:
  - url: http://localhost:8080
    description: Desenvolvimento local

paths:
  /calculator:
    post:
      tags:
        - Calculadora
      summary: Calcular empréstimo
      description: Calcula o plano de pagamento para empréstimos usando sistema PRICE
      operationId: calculateLoan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanCalculatorRequestDTO'
            examples:
              price_simples:
                $ref: '#/components/examples/PriceSimples'
              price_completa:
                $ref: '#/components/examples/PriceCompleta'
      responses:
        '200':
          description: Cálculo realizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanCalculatorResponseDTO'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  examples:
    PriceSimples:
      summary: PRICE Simples
      description: Financiamento básico sem componentes opcionais
      value:
        calculationType: PRICE
        installmentQuantity: 5
        requestedAmount:
          amount: 4000.0
          currency: "BRL"
        contractDate: "2025-04-29"
        firstInstallmentDate: "2025-05-29"
        monthlyInterestRate: 0.0175
    
    PriceCompleta:
      summary: PRICE Completa
      description: Financiamento com todos os componentes (seguro, tarifa e tributos)
      value:
        calculationType: PRICE
        installmentQuantity: 5
        requestedAmount:
          amount: 4000.0
          currency: "BRL"
        contractDate: "2025-04-29"
        firstInstallmentDate: "2025-05-29"
        monthlyInterestRate: 0.0175
        fee:
          paymentType: FINANCED
          totalAmount:
            amount: 200.0
            currency: "BRL"
        insurance:
          paymentType: FINANCED
          totalAmount:
            amount: 800.0
            currency: "BRL"
        tax:
          paymentType: FINANCED
          dailyFinancialOperationalTax:
            amount: 0.0082
            currency: "BRL"
          additionalFinancialOperationalTax:
            amount: 0.38
            currency: "BRL"

  schemas:
    LoanCalculatorRequestDTO:
      type: object
      required:
        - calculationType
        - installmentQuantity
        - requestedAmount
        - contractDate
        - firstInstallmentDate
        - monthlyInterestRate
      properties:
        calculationType:
          $ref: '#/components/schemas/CalculationType'
        installmentQuantity:
          type: integer
          minimum: 1
          maximum: 360
          description: Quantidade de parcelas
          example: 24
        requestedAmount:
          $ref: '#/components/schemas/AmountDTO'
        contractDate:
          type: string
          format: date
          description: Data do contrato
          example: "2024-01-15"
        firstInstallmentDate:
          type: string
          format: date
          description: Data da primeira parcela
          example: "2024-02-15"
        lastInstallmentDate:
          type: string
          format: date
          description: Data da última parcela
          example: "2026-01-15"
        monthlyInterestRate:
          type: number
          format: decimal
          minimum: 0.001
          maximum: 1.0
          description: Taxa de juros mensal (decimal)
          example: 0.025
        insurance:
          $ref: '#/components/schemas/InsuranceRequestDTO'
        fee:
          $ref: '#/components/schemas/FeeRequestDTO'
        tax:
          $ref: '#/components/schemas/TaxRequestDTO'

    LoanCalculatorResponseDTO:
      type: object
      properties:
        requestedAmount:
          $ref: '#/components/schemas/AmountDTO'
        contractDate:
          type: string
          format: date
          description: Data do contrato
          example: "2024-01-15"
        firstInstallmentDate:
          type: string
          format: date
          description: Data da primeira parcela
          example: "2024-02-15"
        lastInstallmentDate:
          type: string
          format: date
          description: Data da última parcela
          example: "2026-01-15"
        monthlyInterestRate:
          type: number
          format: decimal
          description: Taxa de juros mensal
          example: 2.5
        annualInterestRate:
          type: number
          format: decimal
          description: Taxa de juros anual
          example: 34.49
        insurance:
          $ref: '#/components/schemas/InsuranceResponseDTO'
        fee:
          $ref: '#/components/schemas/FeeResponseDTO'
        tax:
          $ref: '#/components/schemas/TaxResponseDTO'
        totalFinancedAmount:
          $ref: '#/components/schemas/AmountDTO'
        totalGrantedAmount:
          $ref: '#/components/schemas/AmountDTO'
        totalLoanAmount:
          $ref: '#/components/schemas/AmountDTO'
        installments:
          type: array
          items:
            $ref: '#/components/schemas/InstallmentResponseDTO'

    InsuranceRequestDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        totalAmount:
          $ref: '#/components/schemas/AmountDTO'

    InsuranceResponseDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        totalAmount:
          $ref: '#/components/schemas/AmountDTO'

    FeeRequestDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        totalAmount:
          $ref: '#/components/schemas/AmountDTO'

    FeeResponseDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        totalAmount:
          $ref: '#/components/schemas/AmountDTO'

    TaxRequestDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        dailyFinancialOperationalTax:
          $ref: '#/components/schemas/AmountDTO'
        additionalFinancialOperationalTax:
          $ref: '#/components/schemas/AmountDTO'
        totalAmount:
          $ref: '#/components/schemas/AmountDTO'

    TaxResponseDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        dailyFinancialOperationalTax:
          $ref: '#/components/schemas/AmountDTO'
        additionalFinancialOperationalTax:
          $ref: '#/components/schemas/AmountDTO'
        totalAmount:
          $ref: '#/components/schemas/AmountDTO'

    InstallmentResponseDTO:
      type: object
      properties:
        installmentNumber:
          type: integer
          description: Número da parcela
          example: 1
        dueDate:
          type: string
          format: date
          description: Data de vencimento
          example: "2024-02-15"
        totalInstalmentValue:
          $ref: '#/components/schemas/AmountDTO'
        totalInterestAmount:
          $ref: '#/components/schemas/AmountDTO'
        totalAmortizationAmount:
          $ref: '#/components/schemas/AmountDTO'
        totalBalanceAmount:
          $ref: '#/components/schemas/AmountDTO'
        totalPresentValue:
          $ref: '#/components/schemas/AmountDTO'

    CalculationType:
      type: string
      enum:
        - PRICE
      description: Tipo de cálculo de amortização

    PaymentType:
      type: string
      enum:
        - FINANCED
        - UPFRONT
      description: Tipo de pagamento

    AmountDTO:
      type: object
      properties:
        amount:
          type: number
          format: decimal
          description: Valor monetário
          example: 50000.00
        currency:
          type: string
          description: Código da moeda
          default: "BRL"
          example: "BRL"

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensagem de erro
        details:
          type: array
          items:
            type: string
          description: Detalhes do erro