openapi: 3.0.3
info:
  title: Loan Calculator API
  description: REST API for loan calculation
  version: 1.0.0
  contact:
    name: DevIO
    email: contato@devio.com.br
servers:
  - url: /loan-calculator/v1
    description: Local development
paths:
  /simulations:
    post:
      tags:
        - Simulations
      summary: Simulate a loan payment plan
      description: Simulate a loan payment plan based on the provided parameters
      operationId: simulateLoan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulationRequestDTO'
            examples:
              simple_price:
                $ref: '#/components/examples/SimplePrice'
              complete_price:
                $ref: '#/components/examples/CompletePrice'
      responses:
        200:
          $ref: '#/components/responses/SimulationPOST200Response'
        400:
          $ref: '#/components/responses/BadRequest'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    SimulationPOST200Response:
      description: Calculation completed successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SimulationResponseDTO'
    BadRequest:
      description: BadRequest error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseDTO'
    UnprocessableEntity:
      description: UnprocessableEntity error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseDTO'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseDTO'
  examples:
    SimplePrice:
      summary: Simple PRICE
      description: Basic financing without optional components
      value:
        calculationType: PRICE
        installmentQuantity: 5
        requestedAmount:
          amount: 4000.0
          currency: "BRL"
        contractDate: "2025-04-29"
        firstInstallmentDate: "2025-05-29"
        monthlyInterestRate: 0.0175
    CompletePrice:
      summary: Complete PRICE
      description: Financing with all components (insurance, fee and taxes)
      value:
        calculationType: PRICE
        installmentQuantity: 5
        requestedAmount:
          amount: 4000.0
          currency: "BRL"
        contractDate: "2025-04-29"
        firstInstallmentDate: "2025-05-29"
        monthlyInterestRate: 0.0175
        fee:
          paymentType: FINANCED
          totalAmount:
            amount: 200.0
            currency: "BRL"
        insurance:
          paymentType: FINANCED
          totalAmount:
            amount: 800.0
            currency: "BRL"
        tax:
          paymentType: FINANCED
          dailyFinancialOperationalTax:
            amount: 0.0082
            currency: "BRL"
          additionalFinancialOperationalTax:
            amount: 0.38
            currency: "BRL"
  schemas:
    SimulationRequestDTO:
      type: object
      properties:
        calculationType:
          $ref: '#/components/schemas/CalculationType'
        installmentQuantity:
          type: integer
          minimum: 1
          maximum: 360
          description: Number of installments
          example: 24
        requestedAmount:
          $ref: '#/components/schemas/AmountRequestDTO'
        contractDate:
          type: string
          format: date
          description: Contract date
          example: "2024-01-15"
        firstInstallmentDate:
          type: string
          format: date
          description: First installment date
          example: "2024-02-15"
        lastInstallmentDate:
          type: string
          format: date
          description: Last installment date
          example: "2026-01-15"
        monthlyInterestRate:
          type: number
          format: decimal
          minimum: 0.001
          maximum: 1.0
          description: Monthly interest rate (decimal)
          example: 0.025
        insurance:
          $ref: '#/components/schemas/InsuranceRequestDTO'
        fee:
          $ref: '#/components/schemas/FeeRequestDTO'
        tax:
          $ref: '#/components/schemas/TaxRequestDTO'
    SimulationResponseDTO:
      type: object
      properties:
        requestedAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
        contractDate:
          type: string
          format: date
          description: Contract date
          example: "2024-01-15"
        firstInstallmentDate:
          type: string
          format: date
          description: First installment date
          example: "2024-02-15"
        lastInstallmentDate:
          type: string
          format: date
          description: Last installment date
          example: "2026-01-15"
        monthlyInterestRate:
          type: number
          format: decimal
          description: Monthly interest rate
          example: 2.5
        annualInterestRate:
          type: number
          format: decimal
          description: Annual interest rate
          example: 34.49
        insurance:
          $ref: '#/components/schemas/InsuranceResponseDTO'
        fee:
          $ref: '#/components/schemas/FeeResponseDTO'
        tax:
          $ref: '#/components/schemas/TaxResponseDTO'
        totalFinancedAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
        totalGrantedAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
        totalLoanAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
        installments:
          type: array
          items:
            $ref: '#/components/schemas/InstallmentResponseDTO'
    InsuranceRequestDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        totalAmount:
          $ref: '#/components/schemas/AmountRequestDTO'
    InsuranceResponseDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        totalAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
    FeeRequestDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        totalAmount:
          $ref: '#/components/schemas/AmountRequestDTO'
    FeeResponseDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        totalAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
    TaxRequestDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        dailyFinancialOperationalTax:
          $ref: '#/components/schemas/AmountRequestDTO'
        additionalFinancialOperationalTax:
          $ref: '#/components/schemas/AmountRequestDTO'
        totalAmount:
          $ref: '#/components/schemas/AmountRequestDTO'
    TaxResponseDTO:
      type: object
      properties:
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        dailyFinancialOperationalTax:
          $ref: '#/components/schemas/AmountResponseDTO'
        additionalFinancialOperationalTax:
          $ref: '#/components/schemas/AmountResponseDTO'
        totalAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
    InstallmentResponseDTO:
      type: object
      properties:
        installmentNumber:
          type: integer
          description: Installment number
          example: 1
        dueDate:
          type: string
          format: date
          description: Due date
          example: "2024-02-15"
        totalInstalmentValue:
          $ref: '#/components/schemas/AmountResponseDTO'
        totalInterestAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
        totalAmortizationAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
        totalBalanceAmount:
          $ref: '#/components/schemas/AmountResponseDTO'
    CalculationType:
      type: string
      enum:
        - PRICE
      description: Amortization calculation type
    PaymentType:
      type: string
      enum:
        - FINANCED
        - UPFRONT
      description: Payment type
    AmountRequestDTO:
      type: object
      properties:
        amount:
          type: number
          format: decimal
          description: Monetary value
          example: 50000.00
        currency:
          type: string
          description: Currency code
          default: "BRL"
          example: "BRL"
    AmountResponseDTO:
      type: object
      properties:
        amount:
          type: number
          format: decimal
          description: Monetary value
          example: 50000.00
        currency:
          type: string
          description: Currency code
          default: "BRL"
          example: "BRL"
    ErrorResponseDTO:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
          example: 400
        error:
          type: string
          description: Error type
          example: "Bad Request"
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
        details:
          type: array
          items:
            type: string
          description: Additional error details