quarkus:
  jackson:
    write-dates-as-timestamps: false
    fail-on-unknown-properties: false
  lambda:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
  package:
    type: native
  native:
    container-build: true
  log:
    level: DEBUG
    category:
      "io.quarkus.amazon.lambda":
        level: DEBUG
    console:
      json: false